[package]
name = "ver-api"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Transaction pool primitives types & Runtime API."
documentation = "https://docs.rs/sp-transaction-pool"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
derive_more = { version = "0.99.2", optional = true }
futures = { version = "0.3.19", optional = true }
log = { version = "0.4.8", optional = true }
serde = { version = "1.0.136", features = ["derive"], optional = true}
sp-api = { version = "4.0.0-dev", default-features = false, path = "../../primitives/api"}
sp-std = { version = "5.0.0", default-features = false, path = "../../primitives/std"}
sp-core = { version = "7.0.0", default-features = false, path = "../../primitives/core"}
sp-blockchain = { version = "4.0.0-dev", optional = true, path = "../../primitives/blockchain"}
sp-ver = { version = "4.0.0-dev", default-features = false, path = "../../primitives/ver"}
sp-runtime = { version = "7.0.0", default-features = false, path = "../../primitives/runtime"}

[features]
default = [ "std" ]
std = [
	"codec/std",
	"derive_more",
	"futures",
	"log",
	"serde",
	"sp-api/std",
	"sp-std/std",
	"sp-blockchain",
	"sp-runtime/std",
	"sp-ver/std",
]
