[package]
name = "extrinsic-shuffler"
version = "0.8.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate block builder"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
log = "0.4.8"
sp-runtime = {default-features = false, version = "3.0.0", path = "../../primitives/runtime" }
sp-api = { default-features = false, version = "3.0.0" , path = "../../primitives/api"}
sp-core = { default-features = false, version = "3.0.0" , path = "../../primitives/core"}
sp-std = { default-features = false, version = '3.0.0' , path = "../../primitives/std"}
sp-block-builder = { default-features=false, version = "3.0.0" , path = "../../primitives/block-builder"}
extrinsic-info-runtime-api = { default-features=false, path='../../primitives/extrinsic-info-runtime-api', version='3.0.0' }
sp-ver = { default-features=false, path='../../primitives/ver', version='0.9.0' }
derive_more = "0.99.2"


[features]
default = ['std']
std = [
    'sp-api/std',
    'sp-std/std',
    'sp-core/std',
    'sp-runtime/std',
    'sp-block-builder/std',
    'sp-ver/std',
    'extrinsic-info-runtime-api/std',
]
