[package]
name = "mangata-types"
version = "0.1.0"
authors = ['Mangata team']
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"]}
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }

sp-core = { version = "7.0.0", default-features = false, path = "../core" }
sp-runtime = { version = "7.0.0", default-features = false, path = "../runtime" }
sp-std = {default-features = false, path = "../std" }

[features]
default = ["std"]
std = [
	'codec/std',
	'scale-info/std',
	'sp-core/std',
	'sp-runtime/std',
]
