[package]
name = "frame-executive"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME executives engine"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
aquamarine = "0.1.12"
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
] }
log = { version = "0.4.17", default-features = false }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
frame-support = { version = "4.0.0-dev", default-features = false, path = "../support" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../system" }
frame-try-runtime = { version = "0.10.0-dev", default-features = false, path = "../try-runtime", optional = true }
sp-core = { version = "21.0.0", default-features = false, path = "../../primitives/core" }
sp-io = { version = "23.0.0", default-features = false, path = "../../primitives/io" }
sp-runtime = { version = "24.0.0", default-features = false, path = "../../primitives/runtime" }
sp-std = { version = "8.0.0", default-features = false, path = "../../primitives/std" }
sp-tracing = { version = "10.0.0", default-features = false, path = "../../primitives/tracing" }
schnorrkel = { version = "0.9.1", features = ["preaudit_deprecated", "u64_backend"], default-features = false}
merlin = { version = "2.0", default-features = false }
extrinsic-shuffler = { version='4.0.0-dev', default-features = false, path = '../../primitives/shuffler'}

[dev-dependencies]
hex-literal = "0.3.4"
array-bytes = "6.1"
sp-keystore = { version = "0.27.0", path = "../../primitives/keystore" }
pallet-balances = { version = "4.0.0-dev", path = "../balances" }
pallet-transaction-payment = { version = "4.0.0-dev", path = "../transaction-payment" }
sp-core = { version = "21.0.0", path = "../../primitives/core" }
sp-inherents = { version = "4.0.0-dev", path = "../../primitives/inherents" }
sp-io = { version = "23.0.0", path = "../../primitives/io" }
sp-version = { version = "22.0.0", path = "../../primitives/version" }
sp-ver = { path = "../../primitives/ver" , features=["helpers"]}

[features]
default = [ "std" ]
with-tracing = [ "sp-tracing/with-tracing" ]
std = [
	"codec/std",
	"log/std",
	"frame-support/std",
	"frame-system/std",
	"frame-try-runtime/std",
	"log/std",
	"pallet-balances/std",
	"pallet-transaction-payment/std",
	"scale-info/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-tracing/std",
	"sp-ver/std",
	"schnorrkel/std",
	"extrinsic-shuffler/std",
	"sp-version/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"frame-try-runtime/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"sp-runtime/try-runtime",
]
