[package]
name = "pallet-vesting-mangata-rpc-runtime-api"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "RPC runtime API for transaction payment FRAME pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
pallet-vesting-mangata = { version = "4.0.0-dev", default-features = false, path = "../../../vesting-mangata" }
sp-api = { version = "4.0.0-dev", default-features = false, path = "../../../../primitives/api" }
sp-runtime = { version = "7.0.0", default-features = false, path = "../../../../primitives/runtime" }
sp-std = { version = "5.0.0", default-features = false, path = "../../../../primitives/std" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"pallet-vesting-mangata/std",
	"sp-api/std",
    "sp-std/std",
	"sp-runtime/std",
]
