on:
  pull_request:
    branches:
      - mangata-dev
  push:
    branches: [ mangata-dev ]

name: build

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install newset Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - name: Install nightly-2020-10-01 with wasm
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-10-01
          target: wasm32-unknown-unknown
      - name: Check Cargo version
        run: |
          cargo --version
      - name: Build UT
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-2020-10-01
          command: build
          args: --tests
      - name: Run UT
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-2020-10-01
          command: test
est
