on:
  pull_request:
    branches:
      - mangata-dev
      - mangata-dev-v4
  push:
    branches: [ mangata-dev ]

name: build

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install newset Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - name: Install nightly-2021-10-19 with wasm
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-10-19
          target: wasm32-unknown-unknown
      - name: Check Cargo version
        run: |
          cargo --version
      - name: Build UT
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-2021-10-19
          command: test
          args: -j1 --no-run
      - name: Run UT
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly-2021-10-19
          command: test
