on:
  pull_request:
    branches:
      - mangata-dev
      - feature/block_builder_module_tests
  push:
    branches: [ mangata-dev ]

name: build

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install newset Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - name: Install nightly with wasm
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
      - name: Check Cargo version
        run: |
          cargo --version
      - name: Build UT
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
          args: --release --tests -j1
      - name: Run UT
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: --release test
